### PR TITLE
Card clean up

### PR DESCRIPTION
**Pull request by tram288**

### CODE REVIEW

**Comment by mchuong1** [comment]
add build folder to .gitignore doesnt need to be in the repo

**Comment by mchuong1** [comment]
spacing isnt consistent between different sizes of screen
image

Looking for a possible solution to this. 
I have tried using Max-height already for this but it doesnt seem to restrict paragraph height
Either that or we can enforce a limit on how many characters shown in the preview

**Comment by t-schell** [comment]
I think if we're going to have the Read more... button then it would make since to have a character limit.

**Comment by mchuong1** [comment]
> I think if we're going to have the Read more... button then it would make since to have a character limit.

I was looking at character length and was thinking around 200-250 would be a good limit

**Review by mchuong1 — APPROVED** [review]

**Pull request merged**
